---
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker-isp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - APP_KEY=base64:0i/69TYaZvFtDnd7GbA1Kfjphn/1yjK3R1Z7mck57r4=
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE="5 */6 * * *"
      - SPEEDTEST_SERVERS=
      - DB_HOST= #optional
      - DB_PORT= #optional
      - DB_DATABASE= #optional
      - DB_USERNAME= #optional
      - DB_PASSWORD= #optional
      - DISPLAY_TIMEZONE=America/New_York #optional
      - PRUNE_RESULTS_OLDER_THAN=60 #optional
    volumes:
      - /home/vfedetz/docker/speedtest-tracker-isp/data:/config
    ports:
      - 8099:80
    restart: unless-stopped
