services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8122:8000/tcp # HTTP control server
      - 9696:9696 # port for prowlarr
      - 8112:8112 # port for deluge
      - 5030:5030 # port for slskd
      - 8191:8191 # port for flaresolverr
      - 8098:80 # port for speedtest-tracker-vpn
      - 5801:5800 # port for jdownloader2
    volumes:
      - /home/vfedetz/docker/gluetun:/gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - VPN_SERVICE_PROVIDER=private internet access
      - VPN_TYPE=openvpn
      - OPENVPN_USER=p5401989
      - OPENVPN_PASSWORD=T9dsApDiHxi0gIzfe9EK
      - SERVER_REGIONS=US Wilmington
      - TZ=America/New_York
      - HTTPPROXY=off #change to on if you wish to enable
      - SHADOWSOCKS=off #change to on if you wish to enable
      - FIREWALL_OUTBOUND_SUBNETS=172.20.0.0/16,192.168.1.0/24 #change this in line with your subnet see note on guide.
#      - FIREWALL_VPN_INPUT_PORTS=40312 #uncomment this line and change the port as per the note on the guide
      - HTTP_CONTROL_SERVER_LOG=on
      - HTTP_CONTROL_SERVER_ADDRESS=:8000
      - UPDATER_PERIOD=24h #update the servers information for the currently in-use VPN service provider.
    labels:
      - com.centurylinklabs.watchtower.enable=false
    restart: unless-stopped

  linuxserver-deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /home/vfedetz/docker/deluge:/config
      - /mnt/data/torrents:/data/torrents
    network_mode: service:gluetun # run on the vpn network
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  linuxserver-prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/vfedetz/docker/prowlarr:/config
    network_mode: service:gluetun # run on the vpn network
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  slskd-slskd:
    image: slskd/slskd:latest
    container_name: slskd
    environment:
      - TZ=America/New_York
      - SLSKD_INSTANCE_NAME=KANseek
      - SLSKD_SHARED_DIR=/music
      - SLSKD_DOWNLOADS_DIR=/downloads/complete
      - SLSKD_INCOMPLETE_DIR=/downloads/incomplete
      - SLSKD_SLSK_USERNAME=vfedetz
      - SLSKD_SLSK_PASSWORD=blue1234
      - SLSKD_USERNAME=vfedetz
      - SLSKD_PASSWORD=7G&jDj@9R%Cf2K
      - SLSKD_REMOTE_CONFIGURATION=true
      #- SLSKD_PUSHBULLET=true
      #- SLSKD_PUSHBULLET_ACCESS_TOKEN="zPmYM0SKBhZD4SDtKYX9beJJPrTnQgEZ"
      #- SLSKD_PUSHBULLET_NOTIFY_ON_PRIVATE_MESSAGE=true
      #- SLSKD_NO_SHARE_SCAN=true
      - SLSKD_SHARE_CACHE_STORAGE_MODE=memory # The type of storage to use for the cache (Memory, Disk)
      - SLSKD_SHARE_CACHE_WORKERS=3 # The number of workers to use while scanning shares
    volumes:
      - /home/vfedetz/docker/slskd:/app
      - /mnt/data/media/music:/music
      - /mnt/data/downloads/soulseek:/downloads
    network_mode: service:gluetun # run on the vpn network
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/New_York
    restart: unless-stopped
    network_mode: service:gluetun # run on the vpn network
    depends_on:
      gluetun:
        condition: service_healthy

  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker-vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - APP_KEY=base64:0i/69TYaZvFtDnd7GbA1Kfjphn/1yjK3R1Z7mck57r4=
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE="0 */6 * * *"
      - SPEEDTEST_SERVERS=
      - DB_HOST= #optional
      - DB_PORT= #optional
      - DB_DATABASE= #optional
      - DB_USERNAME= #optional
      - DB_PASSWORD= #optional
      - DISPLAY_TIMEZONE=America/New_York #optional
      - PRUNE_RESULTS_OLDER_THAN=60 #optional
    volumes:
      - /home/vfedetz/docker/speedtest-tracker-vpn/data:/config
    restart: unless-stopped
    network_mode: service:gluetun # run on the vpn network
    depends_on:
      gluetun:
        condition: service_healthy

  jdownloader-2:
    container_name: jdownloader
    image: jlesage/jdownloader-2:latest
    #ports:
    #  - "5801:5800"
    volumes:
      - "/home/vfedetz/docker/jdownloader-2:/config:rw"
      - "/mnt/data/downloads/jdownloader-2:/output:rw"
    network_mode: service:gluetun # run on the vpn network
    depends_on:
      gluetun:
        condition: service_healthy
    restart: "no"

