version: "2.1"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
    # for some reason sabnzbd was throiwng access errors when mapping folders in the ui unless I did this...
      - PUID=0
      - PGID=0
      - TZ=America/New_York
    volumes:
      - /home/vfedetz/docker/sabnzb:/config
      - /mnt/data/usenet:/data/usenet

    ports:
      - 8080:8080
    restart: unless-stopped