version: '3'

services:

    db:
        image: postgres:16
        container_name: joplin-db
        volumes:
            - /home/vfedetz/docker/joplin/db:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=joplin
         
         
    app:
        image: joplin/server:latest
        container_name: joplin-app
        depends_on:
            - db
        ports:
            - "22300:22300"
        restart: unless-stopped
        environment:
            # APP_PORT: The local port on which the Docker container will listen. 
            #	- This would typically be mapped to port to 443 (TLS) with a reverse proxy.
            #	- If Joplin Server does not need to be accessible over the internet, the port can be mapped to 22300.
            - APP_PORT=22300
            # APP_BASE_URL: This is the base public URL where the service will be running.
            #	- If Joplin Server needs to be accessible over the internet, configure APP_BASE_URL as  follows: https://example.com/joplin. 
            #	- If Joplin Server does not need to be accessible over the internet, set the APP_BASE_URL to your server's hostname. 
            #     For Example: http://[hostname]:22300. The base URL can include the port. (VINCE: base url needed to include port or got origin error)
            - APP_BASE_URL=https://joplin.local.kanvisuals.net
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DATABASE=joplin
            - POSTGRES_USER=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db
            - MAILER_ENABLED=1
            - MAILER_HOST=smtp.gmail.com
            - MAILER_PORT=465
            - MAILER_SECURE=1
            - MAILER_AUTH_USER=vfedetz@gmail.com
            - MAILER_AUTH_PASSWORD=ufalqwpeujgzessz
            - MAILER_NOREPLY_NAME=Joplin
            - MAILER_NOREPLY_EMAIL=joplin-app@email.com