---
version: '3'
services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/vfedetz/docker/kavita:/config
      - /mnt/data:/data
    ports:
      - 5000:5000
    restart: unless-stopped

  # All SMTP settings are configured directly in /config/appsettings.json
  # https://wiki.kavitareader.com/en/guides/misc/email
  kavita-email:
    image: jvmilazz0/kavitaemail:latest
    container_name: kavita-email

    volumes:
      - /home/vfedetz/docker/kavita-email:/app/config
    ports:
      - "5003:5003"
    restart: unless-stopped

  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - /home/vfedetz/docker/calibre:/config
      - /mnt/data:/data
    ports:
      - 8081:8080
      - 8182:8181
      - 8083:8081
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/vfedetz/docker/readarr:/config
      - /mnt/data:/data

    ports:
      - 8787:8787
    restart: unless-stopped