services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/vfedetz/docker/sonarr:/config
      - /mnt/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped 

  prefetcharr:
    image: phueber/prefetcharr:latest
    container_name: prefetcharr
    environment:
      # `jellyfin`, `emby` or `plex`
      - MEDIA_SERVER_TYPE=jellyfin
      # Jellyfin/Emby/Plex baseurl
      - MEDIA_SERVER_URL=https://media.local.kanvisuals.net
      # Jellyfin/Emby API key or plex server token
      - MEDIA_SERVER_API_KEY=58a675b082c2456f9ada8cbace17b9bc
      # Sonarr baseurl
      - SONARR_URL=https://sonarr.local.kanvisuals.net
      # Sonarr API key
      - SONARR_API_KEY=f5c2dd0d18564de28deda5a87be9e96c
      # Logging directory
      - LOG_DIR=/log
      # Log level
      - RUST_LOG=prefetcharr=debug
      # Polling interval in seconds
      - INTERVAL=900
      # The last <NUM> episodes trigger a search
      - REMAINING_EPISODES=2
    volumes:
      - /home/vfedetz/docker/prefetcharr/log:/log
    restart: unless-stopped
      
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/vfedetz/docker/radarr:/config
      - /mnt/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped 


  speakarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: speakarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/vfedetz/docker/speakarr:/config
      - /mnt/data:/data

    ports:
      - 8788:8787
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/vfedetz/docker/bazarr:/config
      - /mnt/data:/data
    ports:
      - 6767:6767
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/vfedetz/docker/lidarr:/config
      - /mnt/data:/data
      # needed for soularr integration
      - /mnt/data/downloads/soulseek/complete:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped

  tdarr:
    container_name: tdarr
    #image: ghcr.io/haveagitgat/tdarr:latest
    image: ghcr.io/haveagitgat/tdarr:2.27.02
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true" # exclude from watchtower auto updating
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=192.168.1.188
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=TIAMAT

    volumes:
      - /home/vfedetz/docker/tdarr/server:/app/server
      - /home/vfedetz/docker/tdarr/configs:/app/configs
      - /home/vfedetz/docker/tdarr/logs:/app/logs
      - /mnt/data:/data
      - /mnt/data/media/tdarr-cache:/temp
    devices:
      - /dev/dri:/dev/dri

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    ports:
      - 5055:5055
    volumes:
      - /home/vfedetz/docker/jellyseerr:/app/config
    restart: unless-stopped

  soularr:
    image: mrusse08/soularr:dev
    restart: unless-stopped
    container_name: soularr
    hostname: soularr
    depends_on:
      - lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      #Script interval in seconds
      - SCRIPT_INTERVAL=3000
    user: "1000:1000"
    volumes:
      #"You can set /downloads to whatever you want but will then need to change the Slskd download dir in your config file"
      - /mnt/data/downloads/soulseek/complete:/downloads
      #Select where you are storing your config file. 
      #Leave "/data" since thats where the script expects the config file to be
      - /home/vfedetz/docker/soularr:/data
