version: '3'

services:
    db:
        image: postgres:16
        container_name: joplin-db
        volumes:
            - ${BASE_DIR}/joplin/db:/var/lib/postgresql/data
        ports:
            - ${JOPLIN_DB_PORT}:5432
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=joplin
         
    app:
        image: joplin/server:latest
        container_name: joplin-app
        depends_on:
            - db
        ports:
            - ${JOPLIN_APP_PORT}:22300
        restart: unless-stopped
        environment:
            # APP_PORT: The local port on which the Docker container will listen. 
            #	- This would typically be mapped to port to 443 (TLS) with a reverse proxy.
            #	- If Joplin Server does not need to be accessible over the internet, the port can be mapped to 22300.
            - APP_PORT=${JOPLIN_APP_PORT}
            # APP_BASE_URL: This is the base public URL where the service will be running.
            #	- If Joplin Server needs to be accessible over the internet, configure APP_BASE_URL as  follows: https://example.com/joplin. 
            #	- If Joplin Server does not need to be accessible over the internet, set the APP_BASE_URL to your server's hostname. 
            #     For Example: http://[hostname]:22300. The base URL can include the port. (VINCE: base url needed to include port or got origin error)
            - APP_BASE_URL=${JOPLIN_URL}
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=joplin
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PORT=${JOPLIN_DB_PORT}
            - POSTGRES_HOST=db
            - MAILER_ENABLED=1
            - MAILER_HOST=${MAILER_HOST}
            - MAILER_PORT=${MAILER_PORT}
            - MAILER_SECURE=1
            - MAILER_AUTH_USER=${MAILER_AUTH_USER}
            - MAILER_AUTH_PASSWORD=${MAILER_AUTH_PASSWORD}
            - MAILER_NOREPLY_NAME=Joplin
            - MAILER_NOREPLY_EMAIL=joplin-app@email.com
