version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:${NPM_VERSION}'
    container_name: npm
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - ${NPM_HTTP_PORT}:80 # Public HTTP Port
      - ${NPM_HTTPS_PORT}:443 # Public HTTPS Port
      - ${NPM_WEB_ADMIN_PORT}:81 # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'

    volumes:
      - ${BASE_DIR}/npm/data:/data
      - ${BASE_DIR}/npm/letsencrypt:/etc/letsencrypt
