version: "3.4"
services:
  paperless-broker:
    container_name: paperless-broker
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /home/vfedetz/docker/paperless/broker:/data

  paperless-db:
    container_name: paperless-db
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - /home/vfedetz/docker/paperless/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  paperless-webserver:
    container_name: paperless-webserver
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - paperless-db
      - paperless-broker
    ports:
      - "8000:8000"
    volumes:
      - /home/vfedetz/docker/paperless/webserver:/usr/src/paperless/data
      - /mnt/data/paperless/media:/usr/src/paperless/media
      - /mnt/data/paperless/export:/usr/src/paperless/export
      - /mnt/data/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://paperless-broker:6379
      PAPERLESS_DBHOST: paperless-db
      # The UID and GID of the user used to run paperless in the container. Set this
      # to your UID and GID on the host so that you have write access to the
      # consumption directory.
      USERMAP_UID: 1028
      USERMAP_GID: 100
      # Adjust this key if you plan to make paperless available publicly. It should
      # be a very long sequence of random characters. You don't need to remember it.
      #PAPERLESS_SECRET_KEY: change-me
      PAPERLESS_TIME_ZONE: America/New_York
      PAPERLESS_OCR_LANGUAGE: eng # The default language to use for OCR
      PAPERLESS_OCR_IMAGE_DPI: 600 # failback value to use in case not embedded in pdf
      PAPERLESS_FILENAME_FORMAT: "{{document_type}}/{{created_year}}/{{created_year}}{{created_month}}{{created_day}}_{{correspondent}}_{{tag_list}} - {{title}}"
      PAPERLESS_CONSUMER_POLLING: 300 # Defaults to 0, which disables polling and uses filesystem notifications.
      PAPERLESS_CONSUMER_POLLING_DELAY: 5
      PAPERLESS_DATE_ORDER: MDY
      PAPERLESS_URL: https://paperless.local.kanvisuals.net # required to work behind reverse proxy
      PAPERLESS_ALLOWED_HOSTS: .kanvisuals.net  ## If you have multiple subdomains pointing towards it
      PAPERLESS_CSRF_TRUSTED_ORIGINS: https://*.kanvisuals.net  ## If you have multiple subdomains pointing towards it
      PAPERLESS_TASK_WORKERS: 2 # Ensure that the product PAPERLESS_TASK_WORKERS * PAPERLESS_THREADS_PER_WORKER does not exceed your CPU core count 
      PAPERLESS_THREADS_PER_WORKER: 1 # Ensure that the product PAPERLESS_TASK_WORKERS * PAPERLESS_THREADS_PER_WORKER does not exceed your CPU core count
      PAPERLESS_WEBSERVER_WORKERS: 1 # This will save some memory.
      PAPERLESS_ENABLE_NLTK: false # disable the more advanced language processing, which can take more memory and processing time.