version: "3.9"

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: tailscale-gluetun
    restart: unless-stopped
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp
      - 8125:8000/tcp
    volumes:
      - ${BASE_DIR}/tailscale-gluetun:/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - PUID=1000
      - PGID=1000
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPNVPN_USER}
      - OPENVPN_PASSWORD=${OPNVPN_PASSWORD}
      - SERVER_REGIONS=${SERVER_REGIONS}
      - TZ=America/New_York
      - HTTPPROXY=off
      - SHADOWSOCKS=off
      - FIREWALL_OUTBOUND_SUBNETS=172.20.0.0/16,192.168.1.0/24
      - HTTP_CONTROL_SERVER_LOG=on
      - HTTP_CONTROL_SERVER_ADDRESS=:8000
      - UPDATER_PERIOD=24h
      - DNS_ADDRESS=${DNS_ADDRESS}
      - MTU_DISCOVERY=off
    labels:
      - "nautical-backup.group=tailscale-vpn-exit-node"
      - "nautical-backup.group.tailscale-vpn-exit-node.priority=101"

  tailscale-vpn-exit-node:
    image: tailscale/tailscale:latest
    container_name: tailscale-vpn-exit-node
    restart: unless-stopped
    network_mode: host   # <-- Use host networking for reliability
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${BASE_DIR}/tailscale-vpn-exit-node:/var/lib/tailscale
    environment:
      # Uncomment TS_AUTHKEY to authenticate the first time, then comment it again
      #- TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-exit-node --accept-routes
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=npm-vpn-exit
      - TS_ROUTES=192.168.1.0/24
      - TS_SOCKS5_SERVER=localhost:1055
    depends_on:
      - gluetun
    labels:
      - "nautical-backup.group=tailscale-vpn-exit-node"
      - "nautical-backup.group.tailscale-vpn-exit-node.priority=100"
