version: '3.4'
services:
  samba:
      image: dperson/samba
      container_name: samba-ps2
      environment:
        TZ: 'EST5EDT'
      networks:
        - default
      ports:
        - "137:137/udp"
        - "138:138/udp"
        - "139:139/tcp"
        - "445:445/tcp"
      read_only: true
      tmpfs:
        - /tmp
      restart: unless-stopped
      stdin_open: true
      tty: true
      volumes:
        - /mnt/data/media/games/ps2/ps2smb:/ps2smb:rw
        #- /mnt/data/media/games/ps2/ps2smb:/ps2smb:z
        #- /home/vfedetz/docker/samba/var/lib/samba:/var/lib/samba
        #- /home/vfedetz/docker/samba/run/samba:/run/samba
        #- /home/vfedetz/docker/samba/var/cache/samba:/var/cache/samba
        #- /home/vfedetz/docker/samba/etc:/etc
        #- /home/vfedetz/docker/samba/var/log/samba:/var/log/samba 
      #command: '-S -u "ps2;ps2passwd" -g "log level = 1" -g "ntlm auth = yes" -g "keepalive = 0" -g "strict sync = no" -g "large readwrite = yes" -s "ps2smb;/ps2smb;yes;no;no;ps2;ps2;ps2"' 
      command: '-S -u "ps2;password" -g "ntlm auth = yes" -s "ps2smb;/ps2smb;yes;no;no;ps2;ps2;ps2"' 